apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-api
  template:
    metadata:
      labels:
        app: gateway-api
    spec:
      containers:
      - name: gateway-api
        image: skyopsacrdev001.azurecr.io/gateway-api:c36a94c0a9f94c8d6da29bd5a2bcb33d92100d52
        ports:
        - containerPort: 8080
        env:
        - name: WeatherApi__BaseUrl
          value: "http://weather-api:8080"