name: SkyOps CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore SkyOps.sln

      - name: Build
        run: dotnet build SkyOps.sln --no-restore --configuration Release

      - name: Build Docker images (no push)
        run: |
          docker build -t skyops/weather-api:test ./src/WeatherApi
          docker build -t skyops/gateway-api:test ./src/GatewayApi
          docker build -t skyops/frontend:test ./src/Frontend